create extension if not exists "pgcrypto";

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  email text not null unique,
  first_name text not null,
  last_name text not null,
  phone text,
  user_type text not null default 'homeowner',
  profile_image text,
  bio text,
  location text,
  is_verified boolean not null default false,
  is_active boolean not null default true,
  email_verified boolean not null default false,
  last_login timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.contractors (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  business_name text not null,
  description text,
  phone text,
  website text,
  license_number text,
  insurance_info text,
  service_areas text[] not null default '{}',
  specialties text[] not null default '{}',
  verified boolean not null default false,
  rating numeric(2,1) not null default 0,
  total_reviews integer not null default 0,
  total_projects integer not null default 0,
  response_time_hours integer not null default 24,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.users(id) on delete cascade,
  contractor_id bigint references public.contractors(id) on delete set null,
  title text not null,
  description text not null,
  category text not null,
  location text not null,
  budget_min numeric(12,2),
  budget_max numeric(12,2),
  status text not null default 'open',
  priority text not null default 'medium',
  start_date date,
  end_date date,
  completion_date date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.project_milestones (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  title text not null,
  description text,
  status text not null default 'pending',
  due_date date,
  completion_date date,
  order_index integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.project_files (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  uploader_id bigint not null references public.users(id) on delete cascade,
  filename text not null,
  original_filename text not null,
  file_type text,
  file_size bigint,
  file_path text not null,
  description text,
  created_at timestamptz not null default now()
);

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade unique,
  contractor_id bigint not null references public.contractors(id) on delete cascade,
  client_id bigint not null references public.users(id) on delete cascade,
  rating integer not null check (rating between 1 and 5),
  title text,
  comment text,
  quality_rating integer check (quality_rating between 1 and 5),
  communication_rating integer check (communication_rating between 1 and 5),
  timeliness_rating integer check (timeliness_rating between 1 and 5),
  professionalism_rating integer check (professionalism_rating between 1 and 5),
  value_rating integer check (value_rating between 1 and 5),
  verified_project boolean not null default false,
  helpful_votes integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.review_responses (
  id bigint generated by default as identity primary key,
  review_id bigint not null unique references public.reviews(id) on delete cascade,
  contractor_id bigint not null references public.contractors(id) on delete cascade,
  response_text text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.profiles (
  id bigint generated by default as identity primary key,
  auth_user_id uuid not null unique,
  email text not null,
  display_name text not null,
  role text not null default 'user' check (role in ('admin', 'user', 'contractor')),
  registration_status text not null default 'active' check (registration_status in ('active', 'pending', 'disabled')),
  email_verified boolean not null default false,
  phone_verified boolean not null default false,
  kyc_status text not null default 'unverified' check (kyc_status in ('unverified', 'pending', 'verified', 'failed')),
  profile_completion_status text not null default 'partial' check (profile_completion_status in ('partial', 'complete')),
  contractor_tier text check (contractor_tier in ('free', 'pro', 'platinum')),
  tier_status text not null default 'active' check (tier_status in ('active', 'past_due', 'canceled', 'trial')),
  stripe_customer_id text,
  current_subscription_id bigint,
  avatar_url text,
  bio text,
  is_suspended boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.local_auth_users (
  id bigint generated by default as identity primary key,
  auth_user_id uuid not null unique,
  email text not null unique,
  password_hash text not null,
  display_name text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles add column if not exists registration_status text not null default 'active'
  check (registration_status in ('active', 'pending', 'disabled'));
alter table public.profiles add column if not exists email_verified boolean not null default false;
alter table public.profiles add column if not exists phone_verified boolean not null default false;
alter table public.profiles add column if not exists kyc_status text not null default 'unverified'
  check (kyc_status in ('unverified', 'pending', 'verified', 'failed'));
alter table public.profiles add column if not exists profile_completion_status text not null default 'partial'
  check (profile_completion_status in ('partial', 'complete'));
alter table public.profiles add column if not exists stripe_customer_id text;
alter table public.profiles add column if not exists current_subscription_id bigint;

create table if not exists public.accounts (
  id bigint generated by default as identity primary key,
  auth_user_id uuid not null unique,
  profile_id bigint unique references public.profiles(id) on delete set null,
  account_type text not null check (account_type in ('client', 'contractor_company', 'admin')),
  email text not null,
  status text not null default 'active' check (status in ('active', 'pending', 'disabled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.profile_pages (
  id bigint generated by default as identity primary key,
  account_id bigint not null unique references public.accounts(id) on delete cascade,
  display_name text not null,
  slug text unique,
  role text not null check (role in ('client', 'contractor_company', 'admin')),
  headline text,
  avatar_url text,
  bio text,
  location text,
  visibility text not null default 'public' check (visibility in ('public', 'private')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.client_profiles (
  id bigint generated by default as identity primary key,
  page_id bigint not null unique references public.profile_pages(id) on delete cascade,
  location text,
  budget_range text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.contractor_company_profiles (
  id bigint generated by default as identity primary key,
  page_id bigint not null unique references public.profile_pages(id) on delete cascade,
  business_name text not null,
  license_number text,
  insurance_status text,
  verified boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.indexed_users (
  id bigint generated by default as identity primary key,
  account_id bigint not null unique references public.accounts(id) on delete cascade,
  profile_page_id bigint not null unique references public.profile_pages(id) on delete cascade,
  role text not null check (role in ('client', 'contractor_company', 'admin')),
  display_name text not null,
  headline text,
  contractor_tier text,
  is_verified boolean not null default false,
  searchable_text text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.identity_verifications (
  id bigint generated by default as identity primary key,
  profile_id bigint not null references public.profiles(id) on delete cascade,
  account_id bigint references public.accounts(id) on delete set null,
  provider text not null default 'stripe_identity',
  provider_session_id text not null unique,
  status text not null default 'requires_input'
    check (status in ('requires_input', 'processing', 'verified', 'canceled', 'failed')),
  failure_reason text,
  metadata jsonb not null default '{}'::jsonb,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.verification_requirements (
  id bigint generated by default as identity primary key,
  account_type text not null check (account_type in ('client', 'contractor_company', 'admin')),
  action text not null,
  requirement text not null,
  is_required boolean not null default true,
  created_at timestamptz not null default now(),
  unique (account_type, action, requirement)
);

create table if not exists public.billing_customers (
  id bigint generated by default as identity primary key,
  profile_id bigint not null unique references public.profiles(id) on delete cascade,
  account_id bigint references public.accounts(id) on delete set null,
  stripe_customer_id text not null unique,
  email text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.subscriptions (
  id bigint generated by default as identity primary key,
  profile_id bigint not null references public.profiles(id) on delete cascade,
  account_id bigint references public.accounts(id) on delete set null,
  stripe_subscription_id text not null unique,
  stripe_customer_id text not null,
  tier text not null check (tier in ('free', 'pro', 'platinum')),
  status text not null check (status in ('trialing', 'active', 'past_due', 'canceled', 'incomplete', 'incomplete_expired', 'unpaid')),
  current_period_start timestamptz,
  current_period_end timestamptz,
  cancel_at timestamptz,
  canceled_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.subscription_events (
  id bigint generated by default as identity primary key,
  profile_id bigint references public.profiles(id) on delete set null,
  account_id bigint references public.accounts(id) on delete set null,
  subscription_id bigint references public.subscriptions(id) on delete set null,
  stripe_event_id text unique,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.invoices (
  id bigint generated by default as identity primary key,
  profile_id bigint references public.profiles(id) on delete set null,
  account_id bigint references public.accounts(id) on delete set null,
  subscription_id bigint references public.subscriptions(id) on delete set null,
  stripe_invoice_id text not null unique,
  status text not null,
  amount_due bigint not null default 0,
  amount_paid bigint not null default 0,
  currency text not null default 'usd',
  hosted_invoice_url text,
  invoice_pdf text,
  period_start timestamptz,
  period_end timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  author_profile_id bigint not null references public.profiles(id) on delete cascade,
  caption text not null,
  category text,
  post_type text not null default 'client_post' check (post_type in ('promotion', 'client_post', 'tradescenter_news', 'showcase')),
  showcase_eligible boolean not null default false,
  visibility text not null default 'public' check (visibility in ('public', 'private')),
  promoted boolean not null default false,
  repost_of_post_id bigint references public.posts(id) on delete set null,
  is_deleted boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.post_media (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  media_url text not null,
  media_type text not null check (media_type in ('image', 'video')),
  phase text check (phase in ('before', 'after')),
  order_index integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  author_profile_id bigint not null references public.profiles(id) on delete cascade,
  parent_comment_id bigint references public.comments(id) on delete cascade,
  content text not null,
  is_deleted boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.reactions (
  id bigint generated by default as identity primary key,
  target_type text not null check (target_type in ('post', 'comment')),
  target_id bigint not null,
  reaction_type text not null check (reaction_type in ('like', 'heart', 'applaud')),
  author_profile_id bigint not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (target_type, target_id, reaction_type, author_profile_id)
);

create table if not exists public.tags (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  label text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.post_tags (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  tag_id bigint not null references public.tags(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (post_id, tag_id)
);

create table if not exists public.post_tagged_profiles (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  tagged_profile_id bigint not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (post_id, tagged_profile_id)
);

create table if not exists public.profile_access_requests (
  id bigint generated by default as identity primary key,
  requester_profile_id bigint not null references public.profiles(id) on delete cascade,
  target_profile_id bigint not null references public.profiles(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending', 'accepted', 'declined')),
  responded_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (requester_profile_id <> target_profile_id)
);

alter table public.profile_pages add column if not exists location text;

create table if not exists public.shares (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  author_profile_id bigint not null references public.profiles(id) on delete cascade,
  share_type text not null check (share_type in ('internal', 'external')),
  external_platform text,
  created_at timestamptz not null default now()
);

create table if not exists public.conversations (
  id bigint generated by default as identity primary key,
  conversation_type text not null check (conversation_type in ('direct', 'project')),
  project_id bigint references public.projects(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.conversation_participants (
  id bigint generated by default as identity primary key,
  conversation_id bigint not null references public.conversations(id) on delete cascade,
  profile_id bigint not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (conversation_id, profile_id)
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint not null references public.conversations(id) on delete cascade,
  sender_profile_id bigint not null references public.profiles(id) on delete cascade,
  content text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.tier_change_requests (
  id bigint generated by default as identity primary key,
  profile_id bigint not null references public.profiles(id) on delete cascade,
  requested_tier text not null check (requested_tier in ('free', 'pro', 'platinum')),
  status text not null default 'pending',
  provider text not null default 'supabase_demo',
  created_at timestamptz not null default now()
);

create index if not exists idx_projects_status on public.projects(status);
create index if not exists idx_projects_category on public.projects(category);
create index if not exists idx_projects_created_at on public.projects(created_at desc);
create index if not exists idx_contractors_rating on public.contractors(rating desc);
create index if not exists idx_reviews_contractor_id on public.reviews(contractor_id);
create index if not exists idx_reviews_created_at on public.reviews(created_at desc);
create index if not exists idx_profiles_role on public.profiles(role);
create index if not exists idx_profile_pages_role on public.profile_pages(role);
create index if not exists idx_indexed_users_role on public.indexed_users(role);
create index if not exists idx_indexed_users_verified on public.indexed_users(is_verified);
create index if not exists idx_identity_verifications_profile on public.identity_verifications(profile_id, created_at desc);
create index if not exists idx_subscriptions_profile on public.subscriptions(profile_id, created_at desc);
create index if not exists idx_subscription_events_profile on public.subscription_events(profile_id, created_at desc);
create index if not exists idx_posts_created_at on public.posts(created_at desc);
create index if not exists idx_posts_promoted on public.posts(promoted);
create index if not exists idx_posts_post_type on public.posts(post_type);
create index if not exists idx_comments_post_id on public.comments(post_id);
create index if not exists idx_comments_parent on public.comments(parent_comment_id);
create index if not exists idx_reactions_target on public.reactions(target_type, target_id);
create index if not exists idx_shares_post on public.shares(post_id);
create index if not exists idx_messages_conversation on public.messages(conversation_id, created_at);
create index if not exists idx_post_tags_post_id on public.post_tags(post_id);
create index if not exists idx_post_tags_tag_id on public.post_tags(tag_id);
create index if not exists idx_post_tagged_profiles_post_id on public.post_tagged_profiles(post_id);
create index if not exists idx_profile_access_requests_target_status on public.profile_access_requests(target_profile_id, status, created_at desc);
create index if not exists idx_profile_access_requests_requester_status on public.profile_access_requests(requester_profile_id, status, created_at desc);
