-- TradesCenter platform v1.5 additive migration
-- Date: 2026-04-23

alter table public.profiles add column if not exists registration_status text not null default 'active'
  check (registration_status in ('active', 'pending', 'disabled'));
alter table public.profiles add column if not exists email_verified boolean not null default false;
alter table public.profiles add column if not exists phone_verified boolean not null default false;
alter table public.profiles add column if not exists kyc_status text not null default 'unverified'
  check (kyc_status in ('unverified', 'pending', 'verified', 'failed'));
alter table public.profiles add column if not exists profile_completion_status text not null default 'partial'
  check (profile_completion_status in ('partial', 'complete'));
alter table public.profiles add column if not exists stripe_customer_id text;
alter table public.profiles add column if not exists current_subscription_id bigint;

create table if not exists public.accounts (
  id bigint generated by default as identity primary key,
  auth_user_id uuid not null unique,
  profile_id bigint unique references public.profiles(id) on delete set null,
  account_type text not null check (account_type in ('client', 'contractor_company', 'admin')),
  email text not null,
  status text not null default 'active' check (status in ('active', 'pending', 'disabled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.profile_pages (
  id bigint generated by default as identity primary key,
  account_id bigint not null unique references public.accounts(id) on delete cascade,
  display_name text not null,
  slug text unique,
  role text not null check (role in ('client', 'contractor_company', 'admin')),
  headline text,
  avatar_url text,
  bio text,
  visibility text not null default 'public' check (visibility in ('public', 'private')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.client_profiles (
  id bigint generated by default as identity primary key,
  page_id bigint not null unique references public.profile_pages(id) on delete cascade,
  location text,
  budget_range text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.contractor_company_profiles (
  id bigint generated by default as identity primary key,
  page_id bigint not null unique references public.profile_pages(id) on delete cascade,
  business_name text not null,
  license_number text,
  insurance_status text,
  verified boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.indexed_users (
  id bigint generated by default as identity primary key,
  account_id bigint not null unique references public.accounts(id) on delete cascade,
  profile_page_id bigint not null unique references public.profile_pages(id) on delete cascade,
  role text not null check (role in ('client', 'contractor_company', 'admin')),
  display_name text not null,
  headline text,
  contractor_tier text,
  is_verified boolean not null default false,
  searchable_text text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.identity_verifications (
  id bigint generated by default as identity primary key,
  profile_id bigint not null references public.profiles(id) on delete cascade,
  account_id bigint references public.accounts(id) on delete set null,
  provider text not null default 'stripe_identity',
  provider_session_id text not null unique,
  status text not null default 'requires_input'
    check (status in ('requires_input', 'processing', 'verified', 'canceled', 'failed')),
  failure_reason text,
  metadata jsonb not null default '{}'::jsonb,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.verification_requirements (
  id bigint generated by default as identity primary key,
  account_type text not null check (account_type in ('client', 'contractor_company', 'admin')),
  action text not null,
  requirement text not null,
  is_required boolean not null default true,
  created_at timestamptz not null default now(),
  unique (account_type, action, requirement)
);

create table if not exists public.billing_customers (
  id bigint generated by default as identity primary key,
  profile_id bigint not null unique references public.profiles(id) on delete cascade,
  account_id bigint references public.accounts(id) on delete set null,
  stripe_customer_id text not null unique,
  email text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.subscriptions (
  id bigint generated by default as identity primary key,
  profile_id bigint not null references public.profiles(id) on delete cascade,
  account_id bigint references public.accounts(id) on delete set null,
  stripe_subscription_id text not null unique,
  stripe_customer_id text not null,
  tier text not null check (tier in ('free', 'pro', 'platinum')),
  status text not null check (status in ('trialing', 'active', 'past_due', 'canceled', 'incomplete', 'incomplete_expired', 'unpaid')),
  current_period_start timestamptz,
  current_period_end timestamptz,
  cancel_at timestamptz,
  canceled_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.subscription_events (
  id bigint generated by default as identity primary key,
  profile_id bigint references public.profiles(id) on delete set null,
  account_id bigint references public.accounts(id) on delete set null,
  subscription_id bigint references public.subscriptions(id) on delete set null,
  stripe_event_id text unique,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.invoices (
  id bigint generated by default as identity primary key,
  profile_id bigint references public.profiles(id) on delete set null,
  account_id bigint references public.accounts(id) on delete set null,
  subscription_id bigint references public.subscriptions(id) on delete set null,
  stripe_invoice_id text not null unique,
  status text not null,
  amount_due bigint not null default 0,
  amount_paid bigint not null default 0,
  currency text not null default 'usd',
  hosted_invoice_url text,
  invoice_pdf text,
  period_start timestamptz,
  period_end timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_profile_pages_role on public.profile_pages(role);
create index if not exists idx_indexed_users_role on public.indexed_users(role);
create index if not exists idx_indexed_users_verified on public.indexed_users(is_verified);
create index if not exists idx_identity_verifications_profile on public.identity_verifications(profile_id, created_at desc);
create index if not exists idx_subscriptions_profile on public.subscriptions(profile_id, created_at desc);
create index if not exists idx_subscription_events_profile on public.subscription_events(profile_id, created_at desc);
