-- Social v2: news feed, showcase, tagging, profile access requests
-- Date: 2026-04-23

alter table public.posts
  add column if not exists post_type text not null default 'client_post'
  check (post_type in ('promotion', 'client_post', 'tradescenter_news', 'showcase'));

alter table public.posts
  add column if not exists showcase_eligible boolean not null default false;

alter table public.post_media
  add column if not exists phase text check (phase in ('before', 'after'));

alter table public.reactions
  drop constraint if exists reactions_reaction_type_check;

alter table public.reactions
  add constraint reactions_reaction_type_check
  check (reaction_type in ('like', 'heart', 'applaud'));

create table if not exists public.tags (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  label text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.post_tags (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  tag_id bigint not null references public.tags(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (post_id, tag_id)
);

create table if not exists public.post_tagged_profiles (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  tagged_profile_id bigint not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (post_id, tagged_profile_id)
);

create table if not exists public.profile_access_requests (
  id bigint generated by default as identity primary key,
  requester_profile_id bigint not null references public.profiles(id) on delete cascade,
  target_profile_id bigint not null references public.profiles(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending', 'accepted', 'declined')),
  responded_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (requester_profile_id <> target_profile_id)
);

alter table public.profile_pages
  add column if not exists location text;

create index if not exists idx_posts_post_type on public.posts(post_type);
create index if not exists idx_post_tags_post_id on public.post_tags(post_id);
create index if not exists idx_post_tags_tag_id on public.post_tags(tag_id);
create index if not exists idx_post_tagged_profiles_post_id on public.post_tagged_profiles(post_id);
create index if not exists idx_profile_access_requests_target_status on public.profile_access_requests(target_profile_id, status, created_at desc);
create index if not exists idx_profile_access_requests_requester_status on public.profile_access_requests(requester_profile_id, status, created_at desc);
